Repository GSG-G8/events-booker, pull requests merged in 2020-06, with the labels that each got.

#148 Setup travis
  .eslintrc.js
  .travis.yml
  __tests__/queries/index.js
  __tests__/routes/index.js
  package-lock.json
  package.json
  server/database/config/build.js
  server/database/config/connection.js
  server/database/config/fakeData.sql
Labels: Awaiting review, Eslint-config, File-Structure, Rules

#156 refactor /register route and RegisterUser component
  __tests__/routes/index.js
  __tests__/routes/register.test.js
  client/src/components/container/user/Registeration/index.js
  server/controller/index.js
  server/controller/routes/user/index.js
  server/controller/routes/user/registerNewUser.js
  server/router/index.js
Labels: Awaiting review, Back-end route, React - Component, refactor

#155 Cancel registration route refactor
  server/controller/routes/user/cancelRegistration.js
  server/middleware/validation.js
Labels: Awaiting review, Back-end route, front-end-route, refactor

#149 Update check user route:
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/components/container/user/EventPage/index.js
  client/src/components/container/user/PopupBtnEvent/PopupBtnEvent.css
  client/src/components/container/user/PopupBtnEvent/PopupBtnEvent.js
  client/src/components/container/user/PopupBtnEventcomp/PopupBtnEventcomp.js
  server/controller/index.js
  server/controller/routes/user/index.js
  server/controller/routes/user/registeration.js
  server/router/index.js
Labels: Awaiting review, Back-end route, front-end-route, refactor

#151 Refactor the admin route
  client/.eslintrc.js
  client/src/components/container/admin/controlPage/MainPage/index.js
  server/controller/routes/admin/getAdmin.js
Labels: For-merge

#147 Refactor users
  client/package-lock.json
  client/src/components/container/admin/controlPage/component/ViewUsers/ViewUsers.js
  server/controller/routes/admin/getUsers.js
Labels: Awaiting review

#161 fix eslint config file
  client/.eslintrc.js
  client/package-lock.json
  client/src/components/container/user/EventPage/index.js
Labels: Awaiting review

#158 refactor attendance
  server/controller/index.js
  server/controller/routes/portal/attendance.js
  server/controller/routes/portal/index.js
  server/middleware/checkPinCode.js
  server/router/index.js
Labels: Awaiting review, refactor

#152 event with date
  client/.eslintrc.js
  client/src/components/container/portal/Attendance/index.js
  server/controller/routes/admin/viewEventsOnDate.js
Labels: Awaiting review, refactor

#146 refactor portal login route
  client/src/components/container/portal/LogInPage/index.js
  server/controller/routes/portal/portalLogainPage.js
  server/middleware/checkPinCode.js
Labels: Awaiting review, refactor

#157 Refactor Event routes
  client/.eslintrc.js
  client/src/components/common/Header/image/logo.svg
  client/src/components/common/Header/index.js
  client/src/components/container/admin/controlPage/component/AddEvent/index.js
  client/src/components/container/admin/controlPage/component/ViewEvents/ViewEvents.js
  client/src/components/container/user/LandingPage/index.js
  server/controller/routes/admin/createEvent.js
  server/controller/routes/admin/deleteEvent.js
  server/controller/routes/user/getEvent.js
Labels: Awaiting review

#169 Fix eslint problem
  client/src/components/container/user/PopupBtnEvent/index.js
  server/controller/routes/user/mainPage.js
  server/controller/routes/user/registeration.js
Labels: Awaiting review

#163 Refactor landing page
  client/src/components/common/Card/index.js
  client/src/components/common/Card/style.css
  client/src/components/common/EventsGrid/index.js
  client/src/components/common/EventsGrid/style.css
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
  client/src/components/common/Header/image/Group_114573.svg
  client/src/components/common/Header/index.js
  client/src/components/common/Header/style.css
  client/src/components/container/user/LandingPage/CardContent.js
  client/src/components/container/user/LandingPage/Categories.js
  client/src/components/container/user/LandingPage/index.js
  client/src/components/container/user/LandingPage/style.css
Labels: Common-Component, For-merge, Front-end, React - Component, enhancement, refactor

#162 add attendance column for user and edit dashboard side-bar style
  client/src/components/container/admin/LogInPage/index.js
  client/src/components/container/admin/UsersPage/TableUser.js
  client/src/components/container/admin/UsersPage/index.js
  client/src/components/container/admin/controlPage/MainPage/index.js
  client/src/components/container/admin/controlPage/MainPage/style.css
  client/src/components/container/user/Registeration/index.js
Labels: Awaiting review, refactor

#164 Test /users route
  __tests__/routes/users.test.js
Labels: Awaiting review, Back-end route, Done, Tests

#173 Test for the admin route
  __tests__/routes/admin.test.js
Labels: Awaiting review, Back-end route, Tests

#170 Test the /event route
  __tests__/routes/event.test.js
Labels: Awaiting review, Back-end route, Tests

#174 Test Get Admin Data query
  __tests__/queries/admin.test.js
Labels: Awaiting review, Tests, queries

#172 back end routes testing
  __tests__/routes/getEventDetails.test.js
  __tests__/routes/getEventUsers.test.js
  __tests__/routes/register.test.js
  server/controller/routes/admin/getEventUsers.js
  server/controller/routes/user/getEventDetails.js
Labels: Awaiting review

#175 change header picture
  client/src/components/common/Header/image/Group_114573.svg
  client/src/components/common/Header/image/header.jpg
  client/src/components/common/Header/index.js
Labels: Awaiting review

#176 make user code bold in the invitation email
  server/controller/routes/user/registeration.js
Labels: Awaiting review

#179 update mobile regular expression
  __tests__/routes/register.test.js
  server/controller/routes/user/registerNewUser.js
  server/controller/routes/user/registeration.js
Labels: Awaiting review

#178 Make Tests for Event Queries
  __tests__/queries/event.test.js
Labels: Request-change, Tests, queries

#180 fix regex pattern error
  server/controller/routes/user/registerNewUser.js
  server/controller/routes/user/registeration.js
Labels: Awaiting review

#177 Refactor attendance comp
  client/src/components/container/portal/Attendance/AttendanceLogout/index.js
  client/src/components/container/portal/Attendance/AttendanceLogout/style.css
  client/src/components/container/portal/Attendance/AttendanceSubmitForm.js
  client/src/components/container/portal/Attendance/CardContent.js
  client/src/components/container/portal/Attendance/Header/Header.css
  client/src/components/container/portal/Attendance/Header/Header.js
  client/src/components/container/portal/Attendance/index.js
  client/src/components/container/portal/Attendance/style.css
  server/database/config/fakeData.sql
Labels: Awaiting review, Front-end, refactor

#181 Fix forms style
  client/src/components/container/portal/Attendance/AttendanceLogout/index.js
  client/src/components/container/portal/Attendance/AttendanceLogout/style.css
Labels: Awaiting review

#171 start make tests
  __tests__/routes/attendance.test.js
  __tests__/routes/eventDate.test.js
  __tests__/routes/loginPortal.test.js
Labels: Awaiting review, Back-end route, Tests

#184 test the cancel user registeration route
  __tests__/routes/cancelUser.test.js
  __tests__/routes/eventDate.test.js
Labels: Awaiting review, Tests

#185 test the login route
  __tests__/routes/login.test.js
Labels: Awaiting review, Tests

#183 Test check user route
  __tests__/routes/checkUser.test.js
  __tests__/routes/eventDate.test.js
Labels: Awaiting review, Tests

#187 fix time format when insert new event
  client/src/components/container/admin/controlPage/component/AddEvent/index.js
Labels: Awaiting review
