Repository GSG-G8/events-booker, pull requests merged in 2020-04, with the labels that each got.

#81 backend refactor
  server/controller/index.js
  server/controller/routes/admin/getUsers.js
  server/controller/routes/admin/index.js
  server/controller/routes/admin/login.js
  server/controller/routes/admin/viewUsers.js
  server/controller/routes/portal/portalLogainPage.js
  server/controller/routes/user/mainPage.js
  server/controller/routes/user/registeration.js
  server/database/config/admin.sql
  server/middleware/checkPassword.js
  server/middleware/checkPinCode.js
  server/middleware/validation.js
  server/router/index.js
Labels: Awaiting review, Back-end

#80 create logout portal
  server/controller/index.js
  server/controller/routes/portal/index.js
  server/controller/routes/portal/portalLogainPage.js
  server/controller/routes/portal/portalLogout.js
  server/middleware/checkPinCode.js
  server/router/index.js
Labels: Awaiting review, Back-end, DataBase

#83 Card component
  client/config-overrides.js
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/common/Card/index.js
  client/src/components/common/Card/style.css
  client/src/components/container/user/EventPage/index.js
  client/src/components/container/user/LandingPage/index.js
Labels: Awaiting review, Common-Component, React - Component

#95 Header component
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/common/Footer/index.js
  client/src/components/common/Header/index.js
  client/src/components/common/Header/style.css
Labels: Awaiting review, Common-Component

#92 Adding the footer component
  client/src/components/App/App.js
  client/src/components/common/Footer/index.js
  client/src/components/common/Footer/style.css
Labels: Awaiting review, Common-Component, Front-end, React - Component

#86 Landing page
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/common/Card/index.js
  client/src/components/common/Card/style.css
  client/src/components/container/user/LandingPage/index.js
  client/src/components/container/user/LandingPage/style.css
  server/database/config/fakeData.sql
  server/database/queries/events/getEvents.js
  server/middleware/checkPassword.js
Labels: Awaiting review, Front-end, React - Component

#100 Add Header component to Landing page
  client/src/components/common/Card/style.css
  client/src/components/common/Header/index.js
  client/src/components/common/Header/style.css
  client/src/components/container/user/LandingPage/index.js
  client/src/components/container/user/LandingPage/style.css
Labels: Awaiting review, Front-end, React - Component

#102 fix tabs order
  client/src/components/container/user/LandingPage/style.css
Labels: Awaiting review, Front-end, enhancement

#94 create event page
  client/config-overrides.js
  client/package-lock.json
  client/package.json
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/container/user/EventPage/index.js
  client/src/components/container/user/EventPage/style.css
  client/src/components/container/user/EventPageContent/EventPageContent.css
  client/src/components/container/user/EventPageContent/EventPageContent.js
  client/src/components/container/user/PopupBtnEventcomp/PopupBtnEventcomp.css
  client/src/components/container/user/PopupBtnEventcomp/PopupBtnEventcomp.js
  package-lock.json
  package.json
  server/controller/routes/user/cancelRegistration.js
  server/controller/routes/user/registeration.js
  server/database/config/fakeData.sql
Labels: Awaiting review, Front-end, React - Component

#82 Registration Page
  client/package-lock.json
  client/src/components/App/App.css
  client/src/components/App/App.js
  client/src/components/container/user/Registeration/index.js
  client/src/components/container/user/Registeration/style.css
  server/controller/routes/user/registerNewUser.js
Labels: Awaiting review, React - Component, front-end-route

#110 Add event's form
  client/src/components/App/App.js
  client/src/components/container/admin/controlPage/component/AddEvent/index.js
  server/controller/routes/admin/createEvent.js
  server/router/index.js
Labels: Awaiting review, Front-end, React - Component

#116 fixed landing page style
  client/src/components/common/Header/style.css
  client/src/components/container/user/LandingPage/index.js
Labels: Awaiting review, Front-end, enhancement

#109 Show events users
  client/src/components/container/admin/controlPage/component/ViewEvents/ViewEvents.css
  client/src/components/container/admin/controlPage/component/ViewEvents/ViewEvents.js
  client/src/components/container/admin/controlPage/component/ViewEvents/index.js
  client/src/components/container/admin/controlPage/component/ViewEvents/style.css
  client/src/components/container/admin/controlPage/component/ViewUsers/ViewUsers.css
  client/src/components/container/admin/controlPage/component/ViewUsers/ViewUsers.js
  client/src/components/container/admin/controlPage/component/ViewUsers/index.js
  client/src/components/container/admin/controlPage/component/ViewUsers/style.css
  server/controller/routes/admin/deleteEvent.js
  server/database/queries/events/expierdEvent.js
Labels: Awaiting review, Front-end, React - Component

#122 add event's from styles
  client/src/components/container/admin/controlPage/component/AddEvent/index.js
  client/src/components/container/admin/controlPage/component/AddEvent/style.css
Labels: Awaiting review, Front-end, enhancement

#106 31 dashboard page
  client/src/components/App/App.js
  client/src/components/container/admin/controlPage/MainPage/index.js
  client/src/components/container/admin/controlPage/MainPage/style.css
  client/src/components/container/admin/controlPage/component/ViewEvents/ViewEvents.css
  client/src/components/container/admin/controlPage/component/ViewEvents/ViewEvents.js
  client/src/components/container/admin/controlPage/component/ViewUsers/ViewUsers.css
  client/src/components/container/user/Registeration/index.js
  client/src/components/container/user/Registeration/style.css
  server/controller/index.js
  server/controller/routes/admin/getAdmin.js
  server/controller/routes/admin/index.js
  server/database/config/admin.sql
  server/database/config/build.sql
  server/database/queries/admin/getAdmins.js
  server/database/queries/admin/index.js
  server/router/index.js
Labels: Awaiting review, React - Component, front-end-route

#111 37 users page
  client/package-lock.json
  client/package.json
  client/src/components/App/App.js
  client/src/components/container/admin/UsersPage/index.js
  client/src/components/container/admin/UsersPage/style.css
Labels: Awaiting review, Front-end, React - Component

#123 Create portal login
  client/src/components/App/App.js
  client/src/components/container/portal/LogInPage/index.js
  client/src/components/container/portal/LogInPage/style.css
  client/src/components/container/user/PopupBtnEventcomp/PopupBtnEventcomp.js
  server/controller/routes/portal/portalLogainPage.js
  server/middleware/checkPinCode.js
Labels: Awaiting review, Front-end, React - Component

#121 create attendance component
  client/src/components/App/App.js
  client/src/components/container/portal/Attendance/index.js
  client/src/components/container/portal/Attendance/style.css
  server/controller/routes/portal/attendance.js
  server/controller/routes/portal/portalLogout.js
  server/database/config/fakeData.sql
Labels: Awaiting review, Front-end, React - Component, front-end-route

#134 Update handling errors
  client/package-lock.json
  client/src/components/container/admin/LogInPage/index.js
  client/src/components/container/user/PopupBtnEventcomp/PopupBtnEventcomp.js
  client/src/components/container/user/Registeration/index.js
  package-lock.json
  server/controller/routes/admin/createEvent.js
  server/controller/routes/admin/deleteEvent.js
  server/controller/routes/admin/logout.js
  server/controller/routes/admin/viewEventsOnDate.js
  server/controller/routes/portal/portalLogout.js
  server/controller/routes/user/cancelRegistration.js
  server/controller/routes/user/registerNewUser.js
  server/controller/routes/user/registeration.js
  server/controller/routes/user/sendSmsMsg.js
  server/middleware/checkEmail.js
  server/middleware/checkPassword.js
  server/middleware/checkPinCode.js
  server/middleware/validation.js
Labels: Done, For-merge, enhancement, refactor

#127 enhancement - event page
  client/src/components/App/App.js
  client/src/components/container/user/EventPage/index.js
  client/src/components/container/user/Registeration/index.js
  server/controller/index.js
  server/controller/routes/user/getEvent.js
  server/controller/routes/user/index.js
  server/database/queries/events/index.js
  server/router/index.js
Labels: Front-end, On progress, enhancement

#139 React authentication
  client/src/components/App/App.js
  client/src/components/Auth/CheckLogged.js
  client/src/components/Auth/WithAuth.js
  client/src/components/container/admin/LogInPage/index.js
  server/app.js
  server/middleware/checkToken.js
  server/middleware/index.js
  server/router/index.js
Labels: Awaiting review

#141 fix event page title
  client/src/components/container/user/EventPage/index.js
Labels: Done, For-merge
